name: Build check on PR

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20' 
        
    - name: Install Dependencies
      working-directory: ./Payments-App
      run: npm install
      
    - name: Generate prisma client
      working-directory: ./Payments-App
      run: npm run db:generate
      
    - name: Run Build
      working-directory: ./Payments-App
      run: npm run build