name: Build, Deploy, and Verify Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-deploy-verify:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push user-app image
      run: |
        docker build -f docker/Dockerfile.user-app -t ayush272002/payments-app-user-app:latest .
        docker push ayush272002/payments-app-user-app:latest

    - name: Build and push bank-webhook image
      run: |
        docker build -f docker/Dockerfile.bank-webhook -t ayush272002/payments-app-bank-webhook:latest .
        docker push ayush272002/payments-app-bank-webhook:latest

    - name: Verify user-app image by pulling
      run: |
        docker pull ayush272002/payments-app-user-app:latest
        docker images | grep ayush272002/payments-app-user-app

    - name: Verify bank-webhook image by pulling
      run: |
        docker pull ayush272002/payments-app-bank-webhook:latest
        docker images | grep ayush272002/payments-app-bank-webhook
