name: Build, Deploy, and Verify Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-deploy-verify:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Prepare Dockerfile for user-app
      run: cp Payments-App/docker/Dockerfile.user-app ./Dockerfile.user-app

    - name: Prepare Dockerfile for bank-webhook
      run: cp Payments-App/docker/Dockerfile.bank-webhook ./Dockerfile.bank-webhook

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push user-app image
      run: |
        docker build -t ayush27002/payments-app-user-app:latest -f ./Dockerfile.user-app ./Payments-App/
        docker push ayush27002/payments-app-user-app:latest

    - name: Build and push bank-webhook image
      run: |
        docker build -t ayush27002/payments-app-bank-webhook:latest -f ./Dockerfile.bank-webhook ./Payments-App/
        docker push ayush27002/payments-app-bank-webhook:latest

    - name: Verify user-app image by pulling
      run: |
        docker pull ayush27002/payments-app-user-app:latest
        docker images | grep ayush27002/payments-app-user-app

    - name: Verify bank-webhook image by pulling
      run: |
        docker pull ayush27002/payments-app-bank-webhook:latest
        docker images | grep ayush27002/payments-app-bank-webhook
